export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';

export const GET_ALL_BRAND = 'GET_ALL_BRAND';

export const CREATE_BRAND = 'CREATE_BRAND';

export const CREATE_SUBCATEGORY = 'CREATE_SUBCATEGORY';

export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const GET_ERROR = 'GET_ERROR';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const GET_PRODUCT_DETALIS = 'GET_PRODUCT_DETALIS';

export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY';

export const GET_ONE_BRAND = 'GET_ONE_BRAND';

export const GET_PRODUCT_LIKE = 'GET_PRODUCT_LIKE';

export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';

export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';

export const VERIFY_PASSWORD = 'VERIFY_PASSWORD';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const CREATE_REVIEW = 'CREATE_REVIEW';

export const GET_ALL_REVIEWS_PRODUCT = 'GET_ALL_REVIEWS_PRODUCT';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';

export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const USER_WISHLIST = 'USER_WISHLIST';

export const ADD_TO_CART = 'ADD_TO_CART';

export const GET_ALL_USER_CART = 'GET_ALL_USER_CART';
